apiVersion: v1
kind: Secret
metadata:
  name: hackathon-api-secrets
  namespace: hackathon
type: Opaque
data:
  AWS_REGION: dXMtZWFzdC0xCg==
  AWS_ACCESS_KEY: QVNJQVEyNldLQUVaQjRZVlk2SUQK
  AWS_SECRET_ACCESS_KEY: NjFGV0wyRklHVURnS09tVW0rb0lzdGpnVnlFT09OVWp4UFh4b08wSAo=
  AWS_AUTH_LAMBDA_FUNC_NAME: QXV0aExhbWJkYUZ1bmN0aW9uCg==
  AWS_VIDEO_LAMBDA_FUNC_NAME: VmlkZW9Qcm9jZXNzaW5nTGFtYmRhRnVuY3Rpb24K
